from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class EventType(str, Enum):
    TURN_STARTED = "turn_started"
    TURN_ENDED = "turn_ended"
    CARD_DRAWN = "card_drawn"
    CARD_PLAYED = "card_played"
    FOLLOWER_SUMMONED = "follower_summoned"
    AMULET_ENTERED = "amulet_entered"
    SPELL_RESOLVED = "spell_resolved"
    FOLLOWER_EVOLVED = "follower_evolved"
    FOLLOWER_SUPER_EVOLVED = "follower_super_evolved"
    SUPER_EVOLUTION_ATTACK_BONUS = "super_evolution_attack_bonus"
    ATTACK_DECLARED = "attack_declared"
    COMBAT_STARTED = "combat_started"
    DAMAGE_DEALT = "damage_dealt"
    DAMAGE_APPLIED = "damage_applied"
    FOLLOWER_DESTROYED = "follower_destroyed"
    AMULET_DESTROYED = "amulet_destroyed"
    GAME_ENDED = "game_ended"
    CARD_BANISHED = "card_banished"
    CARD_ADDED_TO_HAND = "card_added_to_hand"
    CARD_ADDED_TO_DECK = "card_added_to_deck"
    CARD_RETURNED_TO_HAND = "card_returned_to_hand"
    CARD_RETURNED_TO_DECK = "card_returned_to_deck"
    CARD_DISCARDED = "card_discarded"
    DEATH_DETECTED = "death_detected"
    ENTITY_LEFT_PLAY = "entity_left_play"
    DEATH_BATCH_START = "death_batch_start"
    DEATH_BATCH_END = "death_batch_end"
    LAST_WORDS_START = "last_words_start"
    LAST_WORDS_COMPLETE = "last_words_complete"
    DAMAGE_PREVENTED = "damage_prevented"
    BARRIER_CONSUMED = "barrier_consumed"
    BANE_TRIGGERED = "bane_triggered"
    DRAIN_HEALED = "drain_healed"
    LEADER_HEALED = "leader_healed"
    AMBUSH_LOST = "ambush_lost"
    SPELLBOOSTED = "spellboosted"
    GRAVEYARD_ENTERED = "graveyard_entered"
    SHADOWS_CHANGED = "shadows_changed"
    NECROMANCY_ACTIVATED = "necromancy_activated"
    REANIMATE_RESOLVED = "reanimate_resolved"
    GRAVEYARD_CARD_RETURNED = "graveyard_card_returned"
    GRAVEYARD_CARD_SUMMONED = "graveyard_card_summoned"
    GRAVEYARD_CARD_BANISHED = "graveyard_card_banished"
    COOPERATION_CHANGED = "cooperation_changed"
    COMBO_CHANGED = "combo_changed"
    EARTH_SIGILS_CHANGED = "earth_sigils_changed"
    EARTH_SIGILS_MERGED = "earth_sigils_merged"
    EARTH_RITE_ACTIVATED = "earth_rite_activated"
    EARTH_SIGIL_DESTROY_PREVENTED = "earth_sigil_destroy_prevented"
    EFFECT_DESTROY_PREVENTED = "effect_destroy_prevented"
    CARD_FUSED = "card_fused"
    HAND_CARD_TRANSFORMED = "hand_card_transformed"
    HAND_CARD_SUMMONED = "hand_card_summoned"
    CARD_ABILITY_GRANTED = "card_ability_granted"
    DECK_CARD_COST_CHANGED = "deck_card_cost_changed"
    DECK_CARD_TRANSFORMED = "deck_card_transformed"
    DECK_DUPLICATES_BANISHED = "deck_duplicates_banished"
    DECK_REPLACED = "deck_replaced"
    EMPTY_DECK_OUTCOME_CHANGED = "empty_deck_outcome_changed"
    EMPTY_DECK_DRAW_RESOLVED = "empty_deck_draw_resolved"
    LEADER_MAX_HEALTH_CHANGED = "leader_max_health_changed"
    BOARD_CARD_TRANSFORMED = "board_card_transformed"
    CARD_INVOKED = "card_invoked"
    AMULET_ACTIVATED = "amulet_activated"
    FAITH_PLACED = "faith_placed"
    FAITH_VALUE_CHANGED = "faith_value_changed"
    FAITH_CONSUMED = "faith_consumed"
    FAITH_CONSUME_FAILED = "faith_consume_failed"
    FAITH_ABILITY_GRANTED = "faith_ability_granted"
    FAITH_ABILITY_TRIGGERED = "faith_ability_triggered"
    RANDOM_DISTRIBUTION_RESOLVED = "random_distribution_resolved"
    RANDOM_CHOICES_SELECTED = "random_choices_selected"
    MAX_MANA_CHANGED = "max_mana_changed"
    EXTRA_PP_USED = "extra_pp_used"
    EXTRA_PP_REFRESHED = "extra_pp_refreshed"
    EVOLUTION_POINTS_RESTORED = "evolution_points_restored"
    SUPER_EVOLUTION_POINTS_RESTORED = "super_evolution_points_restored"
    UNION_BURST_ACTIVATED = "union_burst_activated"
    FOLLOWER_HEALED = "follower_healed"
    FOLLOWER_STATS_INCREASED = "follower_stats_increased"
    FOLLOWER_STATS_DECREASED = "follower_stats_decreased"
    FOLLOWER_DAMAGED_SURVIVED = "follower_damaged_survived"
    AMULET_COUNTDOWN_CHANGED = "amulet_countdown_changed"
    FOLLOWER_ABILITIES_REMOVED = "follower_abilities_removed"
    FOLLOWER_LAST_WORDS_REMOVED = "follower_last_words_removed"
    LEADER_BARRIER_GRANTED = "leader_barrier_granted"
    LEADER_DAMAGE_MODIFIER_ADDED = "leader_damage_modifier_added"
    EMBLEM_GAINED = "emblem_gained"
    EMBLEM_REMOVED = "emblem_removed"
    EMBLEM_TRIGGERED = "emblem_triggered"
    CARD_LISTENER_TRIGGERED = "card_listener_triggered"
    EMBLEM_COUNTDOWN_CHANGED = "emblem_countdown_changed"
    EMBLEM_EXPIRED = "emblem_expired"
    FOLLOWER_ATTACK_CAPACITY_GRANTED = "follower_attack_capacity_granted"
    HAND_FOLLOWER_STATS_INCREASED = "hand_follower_stats_increased"
    UNION_BURST_GAUGE_CHANGED = "union_burst_gauge_changed"
    FOLLOWER_TURN_END_DESTROY_GRANTED = "follower_turn_end_destroy_granted"
    FOLLOWER_TURN_END_BANISH_GRANTED = "follower_turn_end_banish_granted"
    FOLLOWER_TURN_END_ABILITY_GRANTED = "follower_turn_end_ability_granted"
    FAITH_MODE_SELECTION_BONUS_GRANTED = (
        "faith_mode_selection_bonus_granted"
    )
    MODE_SELECTED = "mode_selected"
    DECK_FOLLOWERS_BUFFED = "deck_followers_buffed"


@dataclass(frozen=True)
class GameEvent:
    type: EventType
    player_index: int
    source_id: int | None = None
    target_id: int | None = None
    amount: int = 0
    metadata: dict[str, object] = field(default_factory=dict)
    listener_sources: tuple[tuple[int, str, int, int], ...] | None = None
    emblem_sources: tuple[tuple[int, int], ...] | None = None
